name: Run Job Scraping Script Script

on:
  schedule:
    - cron: "0 04 * * *" #runs at 22:00 UTC everyday
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
      - name: install dependencies # Install the requirments.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script # run the file to get the data and updae it
        run: |
          python scrape_usa_jobs.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push